(ns bb-depsolve.core.lint
  "The lint command: :local/root anti-pattern detection and fixes."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [hive-dsl.result :as r]
            [bb-depsolve.version.api :as v]
            [bb-depsolve.cli.ui :as ui]
            [bb-depsolve.core.discovery :as discovery]
            [bb-depsolve.core.resolve :as resolve]
            [bb-depsolve.core.resolve.registries :as registries]))

(defn- ensure-gitignore-entry!
  "Add entry to .gitignore if not already present."
  [root-dir entry]
  (let [gitignore (str (fs/path root-dir ".gitignore"))
        content (if (fs/exists? gitignore) (slurp gitignore) "")
        lines (str/split-lines content)]
    (when-not (some #(= (str/trim %) entry) lines)
      (spit gitignore (str content (when-not (str/ends-with? content "\n") "\n") entry "\n"))
      (println (ui/c :green (str "  Added '" entry "' to .gitignore"))))))

(defn- generate-local-deps-edn
  "Generate local.deps.edn content from local dep entries.

   Entries are keyed on their CANONICAL coordinate — the same symbol the
   deps.edn rewrite installs — because a :local/root under any other group id
   is not an override at all, it is an additional unrelated library."
  [local-entries org]
  (let [header ";; local.deps.edn — machine-specific overrides, DO NOT COMMIT\n;; Auto-generated by bb-depsolve lint --fix\n;;\n;; Usage with clj:  clj -Sdeps \"$(cat local.deps.edn)\"\n;; Usage with bb:    add {:local/root ...} overrides to bb.edn aliases\n"
        deps-str (->> local-entries
                      (map (fn [{:keys [lib path]}]
                             (str "  " (v/canonical-lib lib path org)
                                  " {:local/root \"" path "\"}")))
                      (str/join "\n"))]
    (str header "\n{:deps\n {" (str/trim deps-str) "}}\n")))

(defn lint-cmd
  "Lint dep files for anti-patterns. Currently checks for :local/root in deps.edn."
  [{:keys [opts]}]
  (let [{:keys [root org fix skip-dirs depth]
         :or {root "." depth discovery/default-depth}} opts
        root-dir (str (fs/canonicalize root))
        skip-set (if skip-dirs
                   (into #{} (str/split skip-dirs #","))
                   discovery/default-skip-dirs)
        dep-files (discovery/find-dep-files {:root root :skip-dirs skip-set :depth depth})]

    (println (ui/c :bold "Linting dep files for anti-patterns..."))
    (println)

    (let [all-locals (atom [])
          by-file (atom {})]

      (doseq [{:keys [path project]} (remove discovery/shadow-deps-file? dep-files)
              :let [content (slurp path)
                    locals (v/find-local-deps content)]
              :when (seq locals)]
        (doseq [entry locals]
          (swap! all-locals conj (assoc entry :path path :project project)))
        (swap! by-file assoc path {:project project :locals locals :content content}))

      (if (empty? @all-locals)
        (do
          (println (ui/c :green "No anti-patterns found. All clean!"))
          (println))
        (do
          (println (ui/c :yellow (str "WARNING: " (count @all-locals) " :local/root dep(s) found in committed dep files")))
          (println)
          (println (ui/c :dim "  :local/root pins deps to machine-specific paths."))
          (println (ui/c :dim "  This breaks CI, other developers, and production builds."))
          (println (ui/c :dim "  Move local overrides to local.deps.edn (gitignored) instead."))
          (println)

          (doseq [{:keys [project lib path]} @all-locals
                  :let [local-path (:path (first (filter #(= (:lib %) lib) (get-in @by-file [path :locals]))))]]
            (println (ui/format-local-dep-warning project lib local-path)))
          (println)

          (if fix
            (do
              (println (ui/c :bold "Fixing: splitting :local/root deps..."))
              (println)

              (doseq [[file-path {:keys [locals content]}] @by-file
                      :let [project-dir (str (fs/parent file-path))]]

                (let [local-deps-path (str (fs/path project-dir "local.deps.edn"))]
                  (if (fs/exists? local-deps-path)
                    (println (ui/c :yellow (str "  Skipped " (str (fs/relativize root-dir local-deps-path))
                                                " (already exists — merge manually)")))
                    (do
                      (spit local-deps-path (generate-local-deps-edn locals org))
                      (println (ui/c :green (str "  Created " (str (fs/relativize root-dir local-deps-path))))))))

                (ensure-gitignore-entry! project-dir "local.deps.edn")

                (let [updated-content (atom content)
                      replaced (atom 0)]
                  (doseq [{:keys [lib path]} locals
                          :let [github? (v/parse-github-lib lib)]]
                    (if github?
                      (let [dir-name (v/lib-artifact-id lib)
                            tag-result (resolve/resolve-lib-tags root-dir lib dir-name)]
                        (if (r/ok? tag-result)
                          (let [{:keys [tag sha sha-short]} (:ok tag-result)
                                use-sha (or sha-short sha)]
                            (swap! updated-content v/replace-local-with-git lib tag use-sha)
                            (swap! replaced inc)
                            (println (str "  " (ui/c :cyan (str lib))
                                          " -> " (ui/c :green tag) " " (ui/c :dim use-sha))))
                          (println (ui/c :yellow (str "  Could not resolve " lib
                                                      " — remove :local/root manually")))))
                      ;; Not io.github.* — try local sibling dir first, then mvn
                      (let [sibling-dir (v/infer-sibling-dir path)
                            local-dir (when sibling-dir (fs/path root-dir sibling-dir))
                            local-tag (when (and local-dir (fs/directory? (fs/path local-dir ".git")))
                                        (resolve/resolve-local-tags (str local-dir)))]
                        (if-let [latest (and (r/ok? local-tag) (v/latest-tag (:ok local-tag)))]
                          (let [{:keys [tag sha]} latest
                                use-sha (if (<= (count sha) 12) sha (subs sha 0 7))
                                canonical (v/canonical-lib lib path org)]
                            (swap! updated-content v/replace-local-with-git lib tag use-sha canonical)
                            (swap! replaced inc)
                            (println (str "  " (ui/c :cyan (str lib))
                                          (when (not= canonical lib) (str " -> " (ui/c :cyan (str canonical))))
                                          " -> " (ui/c :green tag) " " (ui/c :dim use-sha)
                                          " (local sibling: " sibling-dir ")")))
                          (let [mvn-result (registries/resolve-mvn-latest lib false)]
                            (if (r/ok? mvn-result)
                              (let [version (:ok mvn-result)]
                                (swap! updated-content v/replace-local-with-mvn lib version)
                                (swap! replaced inc)
                                (println (str "  " (ui/c :cyan (str lib))
                                              " -> " (ui/c :green version))))
                              (println (ui/c :yellow (str "  Could not resolve " lib
                                                          " — remove :local/root manually")))))))))

                  (when (pos? @replaced)
                    (spit file-path @updated-content)
                    (println (ui/c :green (str "  Updated " (str (fs/relativize root-dir file-path))))))))

              (println)
              (println (ui/c :green "Done. Review the changes and commit.")))

            (println (ui/c :dim "  Pass --fix to auto-split into local.deps.edn and resolve remote coords."))))))))
