(ns bb-depsolve.core.lint
  "The lint command: :local/root anti-pattern detection and fixes.

   Two distinctions decide what is reported and how it is repaired, both drawn
   by `core.localroot`:

   - Scope. A :local/root under an opt-in dev alias is not a bad pin, it is an
     override that belongs in the untracked local.deps.edn. Re-pinning it to a
     published coordinate would silently change what that alias resolves to, so
     --fix MOVES the alias instead.
   - Reach. A path that stays inside the project's own repo resolves on every
     clone, and a dep file in no git repo is committed nowhere. Neither is a
     violation of the mvn-only rule."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [hive-dsl.result :as r]
            [bb-depsolve.version.api :as v]
            [bb-depsolve.cli.ui :as ui]
            [bb-depsolve.core.discovery :as discovery]
            [bb-depsolve.core.localroot :as lr]
            [bb-depsolve.core.resolve :as resolve]
            [bb-depsolve.core.resolve.registries :as registries]))

(defn- ensure-gitignore-entry!
  "Add entry to .gitignore if not already present."
  [root-dir entry]
  (let [gitignore (str (fs/path root-dir ".gitignore"))
        content (if (fs/exists? gitignore) (slurp gitignore) "")
        lines (str/split-lines content)]
    (when-not (some #(= (str/trim %) entry) lines)
      (spit gitignore (str content (when-not (str/ends-with? content "\n") "\n") entry "\n"))
      (println (ui/c :green (str "  Added '" entry "' to .gitignore"))))))

(def ^:private local-deps-header
  (str ";; local.deps.edn — machine-specific overrides, DO NOT COMMIT\n"
       ";; Auto-generated by bb-depsolve lint --fix\n"
       ";;\n"
       ";; Usage with clj:  clj -Sdeps \"$(cat local.deps.edn)\"\n"
       ";; Usage with bb:    add {:local/root ...} overrides to bb.edn aliases\n"
       ";;\n"
       ";; Comments MUST stay below the map — the -Sdeps argument has to start\n"
       ";; with `{` or the clj CLI reads the whole string as a file path.\n"))

(defn- generate-local-deps-edn
  "Generate local.deps.edn content from local dep entries.

   Entries are keyed on their CANONICAL coordinate — the same symbol the
   deps.edn rewrite installs — because a :local/root under any other group id
   is not an override at all, it is an additional unrelated library.

   A canonical coordinate is emitted AT MOST ONCE. `find-local-deps` reports
   every :local/root OCCURRENCE, so one lib appearing in both :deps and an
   alias (or in two aliases) arrives twice; emitting both yields a duplicate
   key and an unreadable file. First occurrence wins.

   The emitted text MUST start with `{`: the clojure launcher treats a -Sdeps
   argument not starting with `{` as a FILE PATH, so a leading comment makes
   `clj -Sdeps \"$(cat local.deps.edn)\"` fail with the file echoed back as a
   would-be path. Header therefore goes AFTER the map."
  [local-entries org]
  (let [deps-str (->> local-entries
                      (reduce (fn [{:keys [seen lines] :as acc} {:keys [lib path]}]
                                (let [canonical (v/canonical-lib lib path org)]
                                  (if (contains? seen canonical)
                                    acc
                                    {:seen (conj seen canonical)
                                     :lines (conj lines (str "  " canonical
                                                             " {:local/root \"" path "\"}"))})))
                              {:seen #{} :lines []})
                      :lines
                      (str/join "\n"))]
    (str "{:deps\n {" (str/trim deps-str) "}}\n\n" local-deps-header)))

(defn- read-local-deps
  "Existing local.deps.edn content for a project, or nil."
  [project-dir]
  (let [p (fs/path project-dir "local.deps.edn")]
    (when (fs/exists? p) (slurp (str p)))))

(defn- write-local-deps!
  "Merge `alias-src` into the project's local.deps.edn, creating it with the
   usage header when absent. An existing file is MERGED, never skipped: the
   whole point of the move is that the alias ends up somewhere it still runs."
  [project-dir alias-src]
  (let [target   (str (fs/path project-dir "local.deps.edn"))
        existing (read-local-deps project-dir)
        spliced  (lr/splice-alias existing alias-src)
        content  (if existing spliced (str spliced "\n" local-deps-header))]
    (spit target content)
    (if existing
      (println (ui/c :green (str "  Merged into " target)))
      (println (ui/c :green (str "  Created " target))))))

(defn- resolve-published
  "The published coordinate replacing a top-level :local/root, mvn FIRST.

   A git tag is the fallback, not the preference: the house rule is that a
   committed dep file carries :mvn/version, so a lib that is on a registry must
   be pinned there even when it also has tags."
  [root-dir lib path org]
  (let [mvn (registries/resolve-mvn-latest lib false)]
    (if (r/ok? mvn)
      {:kind :mvn :version (:ok mvn)}
      (let [github?   (v/parse-github-lib lib)
            dir-name  (v/lib-artifact-id lib)
            tags      (if github?
                        (resolve/resolve-lib-tags root-dir lib dir-name)
                        (let [sibling (v/infer-sibling-dir path)
                              local   (when sibling (fs/path root-dir sibling))]
                          (when (and local (fs/directory? (fs/path local ".git")))
                            (resolve/resolve-local-tags (str local)))))]
        (when (and tags (r/ok? tags))
          (let [{:keys [tag sha sha-short]} (if github?
                                              (:ok tags)
                                              (v/latest-tag (:ok tags)))
                use-sha (or sha-short (when (and sha (> (count sha) 12)) (subs sha 0 7)) sha)]
            (when tag {:kind :git :tag tag :sha use-sha
                       :canonical (v/canonical-lib lib path org)})))))))

(defn- fix-file!
  "Repair one dep file. Alias-scoped hits move to local.deps.edn; top-level hits
   are re-pinned to a published coordinate. Returns true when the file changed."
  [{:keys [file project-dir hits root-dir org]}]
  (let [{alias-hits :alias deps-hits :deps} (group-by #(:kind (:scope %)) hits)
        content  (atom (slurp file))
        changed? (atom false)]

    (doseq [alias-kw (distinct (map #(:alias (:scope %)) alias-hits))]
      (let [extracted (lr/extract-alias @content alias-kw)]
        (if (:source extracted)
          (do (write-local-deps! project-dir (:source extracted))
              (reset! content (:content extracted))
              (reset! changed? true)
              (println (str "  " (ui/c :cyan (str alias-kw))
                            " -> " (ui/c :green "local.deps.edn :aliases")
                            " " (ui/c :dim "(dev override, not re-pinned)"))))
          (println (ui/c :yellow (str "  Could not extract alias " alias-kw ", move it manually"))))))

    (doseq [{:keys [lib path]} deps-hits]
      (if-let [{:keys [kind version tag sha canonical]} (resolve-published root-dir lib path org)]
        (do (swap! content #(if (= :mvn kind)
                              (v/replace-local-with-mvn % lib version)
                              (v/replace-local-with-git % lib tag sha canonical)))
            (reset! changed? true)
            (println (str "  " (ui/c :cyan (str lib)) " -> "
                          (ui/c :green (if (= :mvn kind) version tag))
                          (when (= :git kind) (str " " (ui/c :dim sha))))))
        (println (ui/c :yellow (str "  Could not resolve " lib " — remove :local/root manually")))))

    (when @changed?
      (ensure-gitignore-entry! project-dir "local.deps.edn")
      (spit file @content)
      (println (ui/c :green (str "  Updated " file))))
    @changed?))

(defn lint-cmd
  "Lint dep files for anti-patterns: committed :local/root deps that only this
   machine can resolve."
  [{:keys [opts]}]
  (let [{:keys [root org fix skip-dirs depth]
         :or {root "." depth discovery/default-depth}} opts
        root-dir (str (fs/canonicalize root))
        skip-set (if skip-dirs
                   (into #{} (str/split skip-dirs #","))
                   discovery/default-skip-dirs)
        dep-files (discovery/find-dep-files {:root root :skip-dirs skip-set :depth depth})
        scanned (for [{:keys [path project]} (remove discovery/shadow-deps-file? dep-files)
                      :let [content (slurp path)]
                      hit (lr/scan content)]
                  (assoc hit :file path :project project
                         :verdict (lr/classify hit path)))
        {:keys [violation in-repo no-repo]} (group-by :verdict scanned)]

    (println (ui/c :bold "Linting dep files for anti-patterns..."))
    (println)

    (when (seq in-repo)
      (println (ui/c :dim (str "  not flagged: " (count in-repo) " :local/root dep(s) point inside their "
                               "own repo (subproject, resolves on every clone)"))))
    (when (seq no-repo)
      (println (ui/c :dim (str "  not flagged: " (count no-repo) " :local/root dep(s) sit in dep files "
                               "that are in no git repo"))))
    (when (or (seq in-repo) (seq no-repo)) (println))

    (if (empty? violation)
      (do (println (ui/c :green "No anti-patterns found. All clean!"))
          (println))
      (do
        (println (ui/c :yellow (str "WARNING: " (count violation)
                                    " :local/root dep(s) found in committed dep files")))
        (println)
        (println (ui/c :dim "  :local/root pins deps to machine-specific paths."))
        (println (ui/c :dim "  This breaks CI, other developers, and production builds."))
        (println (ui/c :dim "  Move local overrides to local.deps.edn (gitignored) instead."))
        (println)

        (doseq [{:keys [project lib path scope]} violation]
          (println (str (ui/format-local-dep-warning project lib path)
                        (when (= :alias (:kind scope))
                          (ui/c :dim (str "  [alias " (:alias scope) "]"))))))
        (println)

        (if fix
          (do
            (println (ui/c :bold "Fixing: splitting :local/root deps..."))
            (println)
            (doseq [[file hits] (group-by :file violation)]
              (fix-file! {:file file
                          :project-dir (str (fs/parent file))
                          :hits hits
                          :root-dir root-dir
                          :org org}))
            (println)
            (println (ui/c :green "Done. Review the changes and commit.")))
          (println (ui/c :dim "  Pass --fix to move dev aliases into local.deps.edn and re-pin the rest.")))))))
