(ns bb-depsolve.wave.help
  "CLI help text."
  (:require [bb-depsolve.ui :as ui]
            [clojure.string :as str]))

(defn help-cmd
  "Print help text for available commands."
  [dispatch-table & _]
  (println (ui/c :bold "bb-depsolve") " — monorepo dependency management")
  (println)
  (println "Usage: bb-depsolve <command> [options]")
  (println)
  (println (ui/c :bold "Commands:"))
  (doseq [{:keys [cmds doc]} dispatch-table
          :when (seq cmds)]
    (printf "  %-14s %s\n" (str/join " " cmds) doc))
  (println)
  (println (ui/c :bold "Common options:"))
  (println "  --root <dir>       Workspace root (default: cwd)")
  (println "  --skip-dirs <csv>  Directories to skip (default: vendor,node_modules,.git,target,...)")
  (println "  --depth <n>        How deep to scan for dep files (default: 1)")
  (println "  --apply            Write changes (default: dry-run)")
  (println)
  (println (ui/c :bold "Sync options:"))
  (println "  --org <name>       GitHub org for internal deps (required for sync)")
  (println)
  (println (ui/c :bold "Upgrade options:"))
  (println "  --pre-release      Include pre-release versions")
  (println)
  (println (ui/c :bold "Lint options:"))
  (println "  --fix              Auto-fix: split :local/root into local.deps.edn")
  (println "  --org <name>       GitHub org for resolving internal deps (used with --fix)")
  (println)
  (println (ui/c :bold "Tree options:"))
  (println "  --tree-depth <n>   Max transitive depth (default: full resolve)")
  (println "  --conflicts-only   Show only deps with version conflicts")
  (println)
  (println (ui/c :bold "Audit options:"))
  (println "  --tree-depth <n>   Include transitive deps (default: direct only)")
  (println)
  (println (ui/c :bold "Graph / impact / cascade:"))
  (println "  --org <name>       GitHub org for internal deps (required)")
  (println "  --lib <project>    Target project (impact)")
  (println "  --from <csv>       Seed projects (cascade; default: everything unpublished)")
  (println "  --format <fmt>     text (default) | edn | dot (graph only)")
  (println "  --no-wait          Plan without waiting for each wave to publish")
  (println "  --await-timeout <ms>  Per-wave publish-wait ceiling (default: 900000)")
  (println "  --major / --minor / --stable   Seed bump: major / minor / major (1.0)")
  (println)
  (println (ui/c :bold "Automation options:"))
  (println "  --commit           Auto-commit dep changes per project (for upgrade/sync/lint)")
  (println)
  (println (ui/c :bold "Release-wave:"))
  (println "  --org <name>       GitHub org (required)")
  (println "  Runs: upgrade → lint --fix → sync → bump-wave → re-sync → push-all"))
